version: "3.3"
services:
  onion:
    build: 
        context: .
        dockerfile: onion-service-docker/Dockerfile
  directory-authority:
    build: 
        context: .
        dockerfile: directory-authority-docker/Dockerfile
    ports:
        - 1234:1234